version: '3.8'

services:
  mariadb:
    image: mariadb
    hostname: mariadb
    container_name: mariadb
    build:
      context: ./Mariadb
      dockerfile: Dockerfile
    expose:
      - "3306" 
    env_file:
      - ./.env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${SQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  nginx:
    image: nginx
    hostname: nginx
    container_name: nginx
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    env_file: ./.env  
    networks:
      - inception  
    depends_on:
      - wordpress  
    ports:
      - "443:443"  
    restart: on-failure

  wordpress:
    image: wordpress
    hostname: wordpress
    container_name: wordpress
    build:
      context: ./Wordpress
      dockerfile: Dockerfile
    env_file: ./.env  
    volumes:
      - wordpress:/var/www/wordpress  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - inception  
    depends_on:
      - mariadb  
    restart: on-failure
    expose:
      - "9000:9000"  

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../data/wp'  
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '../data/mariadb'

networks:
  inception:
    driver: bridge  
